CREATE TABLE stock_analysis (
    id SERIAL PRIMARY KEY,
    trade_date DATE,
    symbol VARCHAR(255),
    gap_percent DOUBLE PRECISION,
    gap_direction VARCHAR(255),
    atr_ratio DOUBLE PRECISION,
    gap_category VARCHAR(255),
    gap_score DOUBLE PRECISION,
    sentiment_score DOUBLE PRECISION,
    sentiment_level VARCHAR(255),
    sentiment_reasoning TEXT,
    headline_details JSONB,
    volume_ratio DOUBLE PRECISION,
    volume_level VARCHAR(255),
    vwap_position DOUBLE PRECISION,
    volume_score DOUBLE PRECISION,
    pcr DOUBLE PRECISION,
    oi_buildup VARCHAR(255),
    max_pain DOUBLE PRECISION,
    iv_percentile DOUBLE PRECISION,
    suggested_strike DOUBLE PRECISION,
    oi_score DOUBLE PRECISION,
    composite_score DOUBLE PRECISION,
    signal_direction VARCHAR(255),
    recommended_action VARCHAR(255),
    claude_reasoning TEXT,
    risk_warnings TEXT,
    confidence_level VARCHAR(255),
    entry_strike DOUBLE PRECISION,
    estimated_premium DOUBLE PRECISION,
    stop_loss DOUBLE PRECISION,
    target DOUBLE PRECISION,
    risk_reward_ratio DOUBLE PRECISION,
    UNIQUE (trade_date, symbol)
);

CREATE INDEX idx_stock_analysis_trade_date ON stock_analysis(trade_date);
CREATE INDEX idx_stock_analysis_symbol ON stock_analysis(symbol);
